"""Module for reading and writing molecular structure files (.gro).

This version keeps behaviour identical to the original:
- same read/write format
- added docstrings, minor typing and a logger
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

import numpy as np

from src.grotools import Residue

import logging

logger = logging.getLogger(__name__)

__all__ = ["read_gro", "write_gro", "output_gro"]


def read_gro(gro_file_path: str) -> list[str]:
    """Read a GRO file and return all lines."""
    if not gro_file_path.endswith(".gro"):
        raise ValueError(" ## gro format is required!")

    with open(gro_file_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    logger.info("gro file was loaded from %s", gro_file_path)
    return lines


def write_gro(
    residues: Sequence[Residue],
    path: str | Path,
    box: np.ndarray | None = None,
    title: str = "Generated by structural_analysis_gb",
) -> None:
    """
    Write a .gro file from a list of Residue objects.

    Matching formatting to original writer.
    """
    path = Path(path)
    natoms = sum(len(r.atoms) for r in residues)

    if box is None:
        box = np.array([10.0, 10.0, 10.0], dtype=float)
    box = np.asarray(box, dtype=float).ravel()
    if box.size != 3:
        raise ValueError("Box must be a 3-element iterable: [Lx, Ly, Lz] in nm.")

    with path.open("w", encoding="utf-8") as f:
        f.write(f"{title}\n")
        f.write(f"{natoms:5d}\n")

        atom_counter = 1
        for residue in residues:
            resid = residue.resid
            resname = residue.resname
            for atom in residue.atoms:
                x, y, z = atom.position
                f.write(
                    f"{resid:5d}{resname:<5}{atom.atomname:>5}{atom_counter:5d}"
                    f"{x:8.3f}{y:8.3f}{z:8.3f}\n"
                )
                atom_counter += 1

        f.write(f"{box[0]:10.5f}{box[1]:10.5f}{box[2]:10.5f}\n")


# ----------------------------------------------------------------------
# Legacy function: kept for backwards compatibility with old code.
# New code should use `write_gro` with Residue objects instead.
# ----------------------------------------------------------------------
def output_gro(residues: list, path: str) -> None:
    """
    Legacy writer for .gro files.

    Expects `residues` as a list of lists of tuples like:
        residue[0] = (resid, resname, atomname, atomnr, position_array)
    """
    natoms = sum(len(residue) for residue in residues)
    with open(path, "w", encoding="utf-8") as f:
        f.write("Generated gro file\n")
        f.write(f"{natoms:5d}\n")
        atom_counter = 1
        for residue in residues:
            resid = residue[0][0]
            resname = residue[0][1]
            for atom in residue:
                atomname = atom[2]
                x, y, z = atom[-1]
                f.write(
                    f"{resid:5d}{resname:<5}{atomname:>5}{atom_counter:5d}"
                    f"{x:8.3f}{y:8.3f}{z:8.3f}\n"
                )
                atom_counter += 1
        f.write("   10.00000   10.00000   10.00000\n")